### ISSUE TITLE
Issue with Installing grafbase in Linux Mint

### ISSUE THREAD

**Issue by keshavkumarhembram** [grafbase/grafbase#597]
**Describe the bug**
I was unable to install Grafbase on my Linux(Mint) device.
 I was using trying to install Grafbase using this command `npm install -g grafbase`. It was giving an error.

**To Reproduce**
1. Use Linux Mint.
2. Open your vscode in any directory.
3. Open the terminal and use the command `npm install -g grafbase`.
4. It will ask for super user access so I used `sudo npm install -g grafbase`.
5. Then I created package file using `npm init -y` and tried to install using `npm install grafbase`.
6. Then I tried superuser access.
7. Output is mentioned below. I have added the whole test. This is my terminal log.

**Expected behavior**
```console
keshav@keshav-ASUS-TUF-Gaming-A15-FA506IC-FA566IC:~/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial$ npm install grafbase
npm ERR! code 1
npm ERR! path /home/keshav/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial/node_modules/grafbase
npm ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! /home/keshav/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial/node_modules/grafbase/get-environment-data.js:54
npm ERR!   const operatingSystem = OPERATING_SYSTEM_TRANSLATIONS[process.platform] ?? process.platform;
npm ERR!                                                                            ^
npm ERR! 
npm ERR! SyntaxError: Unexpected token '?'
npm ERR!     at wrapSafe (internal/modules/cjs/loader.js:915:16)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:963:27)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR!     at Object.<anonymous> (/home/keshav/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial/node_modules/grafbase/postinstall.js:8:32)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/keshav/.npm/_logs/2023-08-12T06_09_57_494Z-debug-0.log
keshav@keshav-ASUS-TUF-Gaming-A15-FA506IC-FA566IC:~/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial$ npm install -g grafbase
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/keshav/.npm/_logs/2023-08-12T06_11_38_451Z-debug-0.log
keshav@keshav-ASUS-TUF-Gaming-A15-FA506IC-FA566IC:~/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial$ sudo npm install grafbase
npm ERR! code 1
npm ERR! path /home/keshav/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial/node_modules/grafbase
npm ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! /home/keshav/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial/node_modules/grafbase/get-environment-data.js:54
npm ERR!   const operatingSystem = OPERATING_SYSTEM_TRANSLATIONS[process.platform] ?? process.platform;
npm ERR!                                                                            ^
npm ERR! 
npm ERR! SyntaxError: Unexpected token '?'
npm ERR!     at wrapSafe (internal/modules/cjs/loader.js:915:16)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:963:27)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR!     at Object.<anonymous> (/home/keshav/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial/node_modules/grafbase/postinstall.js:8:32)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-12T06_12_08_695Z-debug-0.log
keshav@keshav-ASUS-TUF-Gaming-A15-FA506IC-FA566IC:~/[1]DashBoard/[4]Learning/[2]Dev/grafbase-tutorial$ sudo npm install -g grafbase
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/grafbase
npm ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! /usr/local/lib/node_modules/grafbase/get-environment-data.js:54
npm ERR!   const operatingSystem = OPERATING_SYSTEM_TRANSLATIONS[process.platform] ?? process.platform;
npm ERR!                                                                            ^
npm ERR! 
npm ERR! SyntaxError: Unexpected token '?'
npm ERR!     at wrapSafe (internal/modules/cjs/loader.js:915:16)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:963:27)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/grafbase/postinstall.js:8:32)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-12T06_24_53_358Z-debug-0.log
```
**Examples**
If applicable, add examples of input and output to help explain your problem.

**Desktop (please complete the following information):**

- OS: Linux(Mint)
- Version: 5.15.0-78-generic

**Additional context**

**Comment by yoav-lavi** [comment]
Hey @keshavkumarhembram, what Node.js version do you have installed? Judging by the error it doesn't understand the [Nullish Coalescing Operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) which should be supported since Node.js 14.

We Require a minimum of Node.JS 18 (which is the LTS)

**Comment by keshavkumarhembram** [comment]
I have installed same day it should be 20. Something

**Comment by yoav-lavi** [comment]
What does `node --version` return?

**Comment by yoav-lavi** [comment]
Does mint perhaps use a different version for `npm`?

**Comment by yoav-lavi** [comment]
Asking since the errors make it look like it just isn't updated for that syntax

**Comment by yoav-lavi** [comment]
It seems like the system version of Node.js for your version of Mint is 12.22.12 which would explain the issue, perhaps `npm` on mint uses the system version of Node.js directly?

**Comment by keshavkumarhembram** [comment]
Yeah it is 12.22.9.

**Comment by keshavkumarhembram** [comment]
Now, I updated nodejs to v18.17.1. It is working. Thanks :)

**Comment by yoav-lavi** [comment]
Happy that worked!
